<a href="https://colab.research.google.com/github/Anastasia-Makarova/DATA_homeworks/blob/main/DATA_HW_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

1.Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [ ]:
print('\u001b[34;1m 1.Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення. \u001b[0m\n')

a = np.array([i for i in range(1, 11)], dtype=int)
print(a)

 1.Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення. 

[ 1  2  3  4  5  6  7  8  9 10]


2.Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [ ]:
print('\u001b[34;1m 2.Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.\u001b[0m\n')

b = np.zeros((3, 3), dtype=int)
print(b)

 2.Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

[[0 0 0]
 [0 0 0]
 [0 0 0]]


3.Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [ ]:
print('\u001b[34;1m 3.Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.\u001b[0m\n')

c = np.random.randint(1, 11, (5, 5), dtype=int)
print(c)

 3.Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

[[1 2 1 3 9]
 [6 4 5 6 1]
 [8 4 1 4 6]
 [4 4 1 1 9]
 [7 8 7 5 1]]


4.Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [ ]:
print('\u001b[34;1m 4.Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.\u001b[0m\n')

d = np.random.random((4,4))
print(d)

 4.Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

[[0.92508395 0.62858134 0.04489849 0.06823715]
 [0.81873936 0.81021395 0.63228453 0.35463952]
 [0.09689099 0.83275754 0.80559405 0.3578188 ]
 [0.93725179 0.6393551  0.36884359 0.22442525]]


5.Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [ ]:
print('\u001b[34;1m 5.Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.\u001b[0m\n')

e =  np.random.randint(1, 11, 5, dtype=int)
f = np.random.randint(1, 11, 5, dtype=int)

print(f'vector_1: {e}')
print(f'vector_2: {f}')
print(f'addition: {e + f}')
print(f'subtraction: {e - f}')
print(f'multiplication: {e * f}')

 5.Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

vector_1: [3 3 2 5 1]
vector_2: [ 7  2 10  2  7]
addition: [10  5 12  7  8]
subtraction: [-4  1 -8  3 -6]
multiplication: [21  6 20 10  7]


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [ ]:
print('\u001b[34;1m 6.Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.\u001b[0m\n')

g = np.random.randint(11, size=7, dtype=int)
h = np.random.randint(11, size=7, dtype=int)

print(f'vector_1: {g}')
print(f'vector_2: {h}')
print(f'scalar_product: {np.dot(g, h)}')

 6.Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

vector_1: [ 4  3  9 10  1  3  7]
vector_2: [10  8  7  2  1  5  7]
scalar_product: 212


7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [ ]:
print('\u001b[34;1m 7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.\u001b[0m\n')

i = np.random.randint(1, 11, (2, 2), dtype=int)
j = np.random.randint(1, 11, (2, 3), dtype=int)

print (f'matrix 1:\n{i}\n')
print (f'matrix 2:\n{j}\n')
print(f'multiplicated:\n{np.dot(i, j)}')

 7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

matrix 1:
[[ 5 10]
 [ 4  5]]

matrix 2:
[[8 3 1]
 [6 4 9]]

multiplicated:
[[100  55  95]
 [ 62  32  49]]


8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [ ]:
print('\u001b[34;1m 8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.\u001b[0m\n')

k = np.random.randint(1, 11, (3, 3), dtype=int)
print(f'direct matrix:\n{k}\n')

k_inv = np.linalg.inv(k)
print(f'inverted matrix:\n{k_inv}')

 8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

direct matrix:
[[ 7  6  4]
 [ 9  5  4]
 [ 7  9 10]]

inverted matrix:
[[-0.15555556  0.26666667 -0.04444444]
 [ 0.68888889 -0.46666667 -0.08888889]
 [-0.51111111  0.23333333  0.21111111]]


9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [ ]:
print('\u001b[34;1m 9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.\u001b[0m\n')

l = np.random.random((4, 4))
print(f'direct matrix:\n{l}\n')

l_transp = l.T
print(f'transponated matrix:\n{l_transp}')


 9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

direct matrix:
[[0.56799725 0.66132136 0.2900465  0.04149062]
 [0.28431287 0.73675878 0.87348766 0.29716093]
 [0.63976329 0.11077685 0.05178915 0.43507927]
 [0.95931448 0.34906316 0.52127082 0.99512667]]

transponated matrix:
[[0.56799725 0.28431287 0.63976329 0.95931448]
 [0.66132136 0.73675878 0.11077685 0.34906316]
 [0.2900465  0.87348766 0.05178915 0.52127082]
 [0.04149062 0.29716093 0.43507927 0.99512667]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [ ]:
print('\u001b[34;1m 10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.\u001b[0m\n')

m = np.random.randint(1, 11, (3, 4), dtype=int)
print(f'matrix:\n{m}\n')

n = np.random.randint(1, 11, (4), dtype=int)
print(f'vector:\n{n}\n')

print(f'multiplicated:\n{np.dot(m, n)}')

 10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

matrix:
[[3 8 9 3]
 [4 4 1 2]
 [9 2 7 7]]

vector:
[3 2 6 3]

multiplicated:
[88 32 94]


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [ ]:
print('\u001b[34;1m 11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.\u001b[0m\n')

o = np.random.random((2, 3))
print(f'matrix:\n{o}\n')

p = np.random.random((3))
print(f'vector:\n{p}\n')

print(f'multiplicated:\n{np.dot(o, p)}\n')

 11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

matrix:
[[0.07721106 0.6541991  0.24008915]
 [0.25378651 0.75751377 0.45474048]]

vector:
[0.98280263 0.56018723 0.52709138]

multiplicated:
[0.56890613 0.91346138]



12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [ ]:
print('\u001b[34;1m 12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.\u001b[0m\n')

q = np.random.randint(1, 11, (2, 2), dtype=int)
print(f'matrix 1:\n{q}\n')

r = np.random.randint(1, 11, (2, 2), dtype=int)
print(f'matrix 2:\n{r}\n')

print(f'multiplicated:\n{q*r}')

 12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

matrix 1:
[[2 3]
 [3 9]]

matrix 2:
[[10 10]
 [ 2  2]]

multiplicated:
[[20 30]
 [ 6 18]]


13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [ ]:
print('\u001b[34;1m 13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.\u001b[0m\n')

s = np.random.randint(1, 11, (2, 2), dtype=int)
t = np.random.randint(1, 11, (2, 2), dtype=int)

print (f'matrix 1:\n{s}\n')

print (f'matrix 2:\n{t}\n')

print(f'multiplicated:\n{np.matmul(s, t)}')


 13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

matrix 1:
[[ 4 10]
 [ 3 10]]

matrix 2:
[[10  9]
 [ 9  9]]

multiplicated:
[[130 126]
 [120 117]]


14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [ ]:
print('\u001b[34;1m 14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.\u001b[0m\n')

u = np.random.randint(1, 101, (5, 5), dtype=int)
print (f'matrix:\n{u}\n')

print(f'sum of elements:\n{u.sum()}')


 14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

matrix:
[[64 25  4 72 35]
 [60 55 24 44 30]
 [ 8 67 61 54 22]
 [89 37 63 63 62]
 [94 74 30 92 42]]

sum of elements:
1271


15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [ ]:
print('\u001b[34;1m 15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.\u001b[0m\n')

v = np.random.randint(1, 11, (4, 4), dtype=int)
w = np.random.randint(1, 11, (4, 4), dtype=int)

print (f'matrix 1:\n{v}\n')

print (f'matrix 2:\n{w}\n')

print(f'substraction:\n{v - w}')


 15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

matrix 1:
[[ 4  7 10  7]
 [ 1  3  5  2]
 [ 1  8  4 10]
 [ 6  2  9  4]]

matrix 2:
[[ 3  8  4  6]
 [ 6  7  8  1]
 [10  9  4  2]
 [ 8  8  6  5]]

substraction:
[[ 1 -1  6  1]
 [-5 -4 -3  1]
 [-9 -1  0  8]
 [-2 -6  3 -1]]


16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [ ]:
print('\u001b[34;1m 16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.\u001b[0m\n')

x = np.random.random((3, 3))
print(f'matrix:\n{x}\n')

x_vect = np.array([[line.sum()] for line in x])
print(f'vector:\n{x_vect}\n')


 16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

matrix:
[[0.41466005 0.86273369 0.02300789]
 [0.86260936 0.9002304  0.76807923]
 [0.4991445  0.28642756 0.17069164]]

vector:
[[1.30040162]
 [2.53091899]
 [0.9562637 ]]



17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [ ]:
print('\u001b[34;1m 17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.\u001b[0m\n')


y = np.random.randint(1, 11, (3, 4), dtype=int)
print (f'matrix:\n{y}\n')

y_pow = np.power(y, 2)
print(f'squares:\n{y_pow}\n')


 17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

matrix:
[[ 2 10  9  3]
 [ 2  1  3  5]
 [ 1 10  1  1]]

squares:
[[  4 100  81   9]
 [  4   1   9  25]
 [  1 100   1   1]]



18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [ ]:
print('\u001b[34;1m 18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.\u001b[0m\n')

z = np.random.randint(1, 51, (4), dtype=int)
print (f'vector:\n{z}\n')

z_sqrt = np.sqrt(z)
print(f'square roots:\n{z_sqrt}\n')


 18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

vector:
[ 3 20 46 17]

square roots:
[1.73205081 4.47213595 6.78232998 4.12310563]

